-- Autogenerated by migration tool on 2022-04-04 17:13:07
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: codepipeline.pipelines
DROP TABLE IF EXISTS aws_codepipeline_pipeline_stage_actions;
DROP TABLE IF EXISTS aws_codepipeline_pipeline_stages;
DROP TABLE IF EXISTS aws_codepipeline_pipelines;

-- Resource: sns.subscriptions
ALTER TABLE IF EXISTS aws_sns_subscriptions DROP CONSTRAINT aws_sns_subscriptions_pk;
ALTER TABLE IF EXISTS aws_sns_subscriptions ADD CONSTRAINT aws_sns_subscriptions_pk PRIMARY KEY (cq_fetch_date,arn);
