-- Autogenerated by migration tool on 2022-04-06 08:56:52
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: codepipeline.pipelines
DROP TABLE IF EXISTS aws_codepipeline_pipeline_stage_actions;
DROP TABLE IF EXISTS aws_codepipeline_pipeline_stages;
DROP TABLE IF EXISTS aws_codepipeline_pipelines;

-- Resource: mq.brokers
ALTER TABLE IF EXISTS aws_mq_brokers DROP CONSTRAINT aws_mq_brokers_pk;
ALTER TABLE IF EXISTS aws_mq_brokers ADD CONSTRAINT aws_mq_brokers_pk PRIMARY KEY (cq_fetch_date,account_id,broker_id);
ALTER TABLE IF EXISTS aws_mq_broker_configurations DROP CONSTRAINT aws_mq_broker_configurations_pk;
ALTER TABLE IF EXISTS aws_mq_broker_configurations ADD CONSTRAINT aws_mq_broker_configurations_pk PRIMARY KEY (cq_fetch_date,broker_cq_id,id);
DROP TABLE IF EXISTS aws_mq_broker_configuration_revisions;
ALTER TABLE IF EXISTS aws_mq_broker_users DROP CONSTRAINT aws_mq_broker_users_pk;
ALTER TABLE IF EXISTS aws_mq_broker_users ADD CONSTRAINT aws_mq_broker_users_pk PRIMARY KEY (cq_fetch_date,broker_cq_id,username);
ALTER TABLE IF EXISTS "aws_mq_brokers" DROP COLUMN IF EXISTS "id";
ALTER TABLE IF EXISTS "aws_mq_brokers" ADD COLUMN IF NOT EXISTS "broker_id" text;

-- Resource: sns.subscriptions
ALTER TABLE IF EXISTS aws_sns_subscriptions DROP CONSTRAINT aws_sns_subscriptions_pk;
ALTER TABLE IF EXISTS aws_sns_subscriptions ADD CONSTRAINT aws_sns_subscriptions_pk PRIMARY KEY (cq_fetch_date,arn);
