-- Autogenerated by migration tool on 2022-04-12 11:26:28
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: ec2.egress_only_internet_gateways
CREATE TABLE IF NOT EXISTS "aws_ec2_egress_only_internet_gateways" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"cq_fetch_date" timestamp without time zone NOT NULL,
	"account_id" text,
	"region" text,
	"arn" text,
	"attachments" jsonb,
	"id" text,
	"tags" jsonb,
	CONSTRAINT aws_ec2_egress_only_internet_gateways_pk PRIMARY KEY(cq_fetch_date,arn),
	UNIQUE(cq_fetch_date,cq_id)
);
SELECT setup_tsdb_parent('aws_ec2_egress_only_internet_gateways');
