-- Autogenerated by migration tool on 2022-04-19 08:11:58
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: backup.global_settings
DROP TABLE IF EXISTS aws_backup_global_settings;

-- Resource: backup.region_settings
DROP TABLE IF EXISTS aws_backup_region_settings;
-- Resource: ecs.task_definitions
ALTER TABLE IF EXISTS "aws_ecs_task_definitions" DROP COLUMN IF EXISTS "ephemeral_storage_size";
ALTER TABLE IF EXISTS "aws_ecs_task_definitions" DROP COLUMN IF EXISTS "runtime_platform_cpu_architecture";
ALTER TABLE IF EXISTS "aws_ecs_task_definitions" DROP COLUMN IF EXISTS "runtime_platform_os_family";
