-- Autogenerated by migration tool on 2022-04-24 08:54:29
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: elasticbeanstalk.application_versions
DROP TABLE IF EXISTS aws_elasticbeanstalk_application_versions;
