-- Autogenerated by migration tool on 2022-05-09 08:54:40
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: xray.groups
CREATE TABLE IF NOT EXISTS "aws_xray_groups" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"cq_fetch_date" timestamp without time zone NOT NULL,
	"account_id" text,
	"region" text,
	"filter_expression" text,
	"arn" text,
	"group_name" text,
	"insights_enabled" boolean,
	"notifications_enabled" boolean,
	CONSTRAINT aws_xray_groups_pk PRIMARY KEY(cq_fetch_date,arn),
	UNIQUE(cq_fetch_date,cq_id)
);
SELECT setup_tsdb_parent('aws_xray_groups');

-- Resource: xray.sampling_rules
CREATE TABLE IF NOT EXISTS "aws_xray_sampling_rules" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"cq_fetch_date" timestamp without time zone NOT NULL,
	"account_id" text,
	"region" text,
	"created_at" timestamp without time zone,
	"modified_at" timestamp without time zone,
	"fixed_rate" float,
	"http_method" text,
	"host" text,
	"priority" integer,
	"reservoir_size" integer,
	"resource_arn" text,
	"service_name" text,
	"service_type" text,
	"url_path" text,
	"version" integer,
	"attributes" jsonb,
	"arn" text,
	"rule_name" text,
	CONSTRAINT aws_xray_sampling_rules_pk PRIMARY KEY(cq_fetch_date,arn),
	UNIQUE(cq_fetch_date,cq_id)
);
SELECT setup_tsdb_parent('aws_xray_sampling_rules');
