-- Autogenerated by migration tool on 2022-05-17 17:23:32
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: waf.web_acls
DROP TABLE IF EXISTS aws_waf_web_acl_logging_configuration;

-- Resource: wafv2.web_acls
DROP TABLE IF EXISTS aws_wafv2_web_acl_logging_configuration;
