// Code generated by internal/generators/main.go; DO NOT EDIT.

package sqs

import (
	"context"
	"encoding/json"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/cloudcontrol"
	"github.com/cloudquery/cq-provider-aws/client"
	"github.com/cloudquery/cq-provider-sdk/provider/diag"
	"github.com/cloudquery/cq-provider-sdk/provider/schema"
	"golang.org/x/sync/errgroup"
)

func Aws_sqs_queue() *schema.Table {
  return &schema.Table{
    Name: "cloudcontrol_aws_sqs_queue",
    Description: "aws_sqs_queue",
    Resolver: fetchaws_sqs_queue,
    Multiplex: client.ServiceAccountRegionMultiplexer(""),
    DeleteFilter: client.DeleteAccountRegionFilter,
    Columns: []schema.Column {
    	{
				Name: "account_id",
				Type: schema.TypeString,
			},
      {
				Name: "region",
				Type: schema.TypeString,
			},
      
      {
        Name: "Arn",
        Description: `Amazon Resource Name (ARN) of the queue.`,
        Type: schema.TypeString,
      },
      {
        Name: "DelaySeconds",
        Description: `The time in seconds for which the delivery of all messages in the queue is delayed. You can specify an integer value of 0 to 900 (15 minutes). The default value is 0.`,
        Type: schema.TypeFloat,
      },
      {
        Name: "KmsDataKeyReusePeriodSeconds",
        Description: `The length of time in seconds for which Amazon SQS can reuse a data key to encrypt or decrypt messages before calling AWS KMS again. The value must be an integer between 60 (1 minute) and 86,400 (24 hours). The default is 300 (5 minutes).`,
        Type: schema.TypeFloat,
      },
      {
        Name: "SqsManagedSseEnabled",
        Description: `Enables server-side queue encryption using SQS owned encryption keys. Only one server-side encryption option is supported per queue (e.g. SSE-KMS or SSE-SQS ).`,
        Type: schema.TypeBool,
      },
      {
        Name: "ContentBasedDeduplication",
        Description: `For first-in-first-out (FIFO) queues, specifies whether to enable content-based deduplication. During the deduplication interval, Amazon SQS treats messages that are sent with identical content as duplicates and delivers only one copy of the message.`,
        Type: schema.TypeBool,
      },
      {
        Name: "FifoQueue",
        Description: `If set to true, creates a FIFO queue. If you don't specify this property, Amazon SQS creates a standard queue.`,
        Type: schema.TypeBool,
      },
      {
        Name: "KmsMasterKeyId",
        Description: `The ID of an AWS managed customer master key (CMK) for Amazon SQS or a custom CMK. To use the AWS managed CMK for Amazon SQS, specify the (default) alias alias/aws/sqs.`,
        Type: schema.TypeString,
      },
      {
        Name: "ReceiveMessageWaitTimeSeconds",
        Description: `Specifies the duration, in seconds, that the ReceiveMessage action call waits until a message is in the queue in order to include it in the response, rather than returning an empty response if a message isn't yet available. You can specify an integer from 1 to 20. Short polling is used as the default or when you specify 0 for this property.`,
        Type: schema.TypeFloat,
      },
      {
        Name: "Tags",
        Description: `The tags that you attach to this queue.`,
        Type: schema.TypeJSON,
      },
      {
        Name: "VisibilityTimeout",
        Description: `The length of time during which a message will be unavailable after a message is delivered from the queue. This blocks other components from receiving the same message and gives the initial component time to process and delete the message from the queue. Values must be from 0 to 43,200 seconds (12 hours). If you don't specify a value, AWS CloudFormation uses the default value of 30 seconds.`,
        Type: schema.TypeFloat,
      },
      {
        Name: "QueueUrl",
        Description: `URL of the source queue.`,
        Type: schema.TypeString,
      },
      {
        Name: "DeduplicationScope",
        Description: `Specifies whether message deduplication occurs at the message group or queue level. Valid values are messageGroup and queue.`,
        Type: schema.TypeString,
      },
      {
        Name: "FifoThroughputLimit",
        Description: `Specifies whether the FIFO queue throughput quota applies to the entire queue or per message group. Valid values are perQueue and perMessageGroupId. The perMessageGroupId value is allowed only when the value for DeduplicationScope is messageGroup.`,
        Type: schema.TypeString,
      },
      {
        Name: "MaximumMessageSize",
        Description: `The limit of how many bytes that a message can contain before Amazon SQS rejects it. You can specify an integer value from 1,024 bytes (1 KiB) to 262,144 bytes (256 KiB). The default value is 262,144 (256 KiB).`,
        Type: schema.TypeFloat,
      },
      {
        Name: "QueueName",
        Description: `A name for the queue. To create a FIFO queue, the name of your FIFO queue must end with the .fifo suffix.`,
        Type: schema.TypeString,
      },
      {
        Name: "RedriveAllowPolicy",
        Description: `The string that includes the parameters for the permissions for the dead-letter queue redrive permission and which source queues can specify dead-letter queues as a JSON object.`,
        Type: schema.TypeString,
      },
      {
        Name: "RedrivePolicy",
        Description: `A string that includes the parameters for the dead-letter queue functionality (redrive policy) of the source queue.`,
        Type: schema.TypeString,
      },
      {
        Name: "MessageRetentionPeriod",
        Description: `The number of seconds that Amazon SQS retains a message. You can specify an integer value from 60 seconds (1 minute) to 1,209,600 seconds (14 days). The default value is 345,600 seconds (4 days).`,
        Type: schema.TypeFloat,
      },
    },
  }
}


func fetchaws_sqs_queue(ctx context.Context, meta schema.ClientMeta, parent *schema.Resource, res chan<- interface{}) error {
  config := cloudcontrol.ListResourcesInput{
		TypeName:   aws.String("AWS::SQS::Queue"),
		MaxResults: aws.Int32(100),
	}
	c := meta.(*client.Client)
  svc := cloudcontrol.NewFromConfig(c.AWSCfg.Copy(), func(o *cloudcontrol.Options) {
		o.Region = c.Region
	})
	for {
		listResources, err := svc.ListResources(ctx, &config)
		if err != nil {
			return diag.WrapError(err)
		}
		// batchResults := make([]map[string]interface{}, len(listResources.ResourceDescriptions))
		errGroup, ctx := errgroup.WithContext(ctx)
		for _, item := range listResources.ResourceDescriptions {
			// i := i
			it := item
			errGroup.Go(func() error {
				r, err := svc.GetResource(ctx, &cloudcontrol.GetResourceInput{
					Identifier: it.Identifier,
					TypeName:   aws.String("AWS::SQS::Queue"),
				})
				if err != nil {
					return diag.WrapError(err)
				}
				var resourceJson map[string]interface{}
				if err := json.Unmarshal([]byte(*r.ResourceDescription.Properties), &resourceJson); err != nil {
					return diag.WrapError(err)
				}
				resourceJson["Arn"] = *it.Identifier
				resourceJson["account_id"] = c.AccountID
        resourceJson["region"] = c.Region
				res <- resourceJson
				return nil
			})
		}
		if err := errGroup.Wait(); err != nil {
			return diag.WrapError(err)
		}
		// res <- batchResults
		if aws.ToString(listResources.NextToken) == "" {
			break
		}
		config.NextToken = listResources.NextToken
	}

	return nil
}
