name: 🐛 Bug Report
description: If something isn't working as expected 🤔.
title: "(short issue description)"
labels: [bug, needs-triage]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Tell us what should happen.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: |
        Provide a list of all steps and commands required to reproduce this issue.
        Also, please provide config.hcl with any PII (such as account number) reducted.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: |
        Suggest a fix/reason for the bug
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Provider and CloudQuery version
      description: |
        output of `cloudquery version` and provider version.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Add any other context or examples about the feature request here.
    validations:
      required: false
