name: "\U0001F680 New Resource"
description: Ask for support of a new resource or service
title: "(short issue description)"
labels: [feature-request, needs-triage]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the resource.
      description: Please link to official API that can fetch the needed resources.
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: |
        Please tell us about the use case so we can understand better the request and potentially
        open other follow-up improvments.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: |
        Any additonal context or information that might help. 
    validations:
      required: false
