{
 "title": "AWS Compliance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_id",
    "query": "select account_id from aws_policy_results"
   },
   {
    "name": "framework",
    "query": "select framework from aws_policy_results"
   },
   {
    "name": "status",
    "query": "select status from aws_policy_results"
   }
  ]
 },
 "panels": [
  {
   "title": "Policy Pass/Fail Distribution",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n  -- execution_time as time,\n  framework,\n  count(case when status = 'fail' then 1 else null end) as fail,\n  -- count(*)\n  count(case when status = 'pass' then 1 else null end) as pass\nfrom aws_policy_results where account_id in (${account_id}) and framework in (${framework}) group by framework;"
    }
   ]
  },
  {
   "title": "Failed Checks",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  execution_time as time,\n  count(*)\nfrom aws_policy_results where account_id in (${account_id}) and framework in (${framework}) and status = 'fail' and $__timeFilter(execution_time) group by execution_time;"
    }
   ]
  },
  {
   "title": "Passed Checks",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  execution_time as time,\n  count(*)\nfrom aws_policy_results where account_id in (${account_id}) and framework in (${framework}) and status = 'pass' and $__timeFilter(execution_time) group by execution_time;"
    }
   ]
  },
  {
   "title": "Policy Results",
   "type": "table",
   "description": "All policies, benchmarks results.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select * from aws_policy_results where account_id in (${account_id}) and framework in (${framework}) and status in (${status}) ;"
    }
   ]
  }
 ]
}