// Code generated by internal/generators/main.go; DO NOT EDIT.

package cloudwatch

import (
	"context"
	"encoding/json"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/cloudcontrol"
	"github.com/cloudquery/cq-provider-aws/client"
	"github.com/cloudquery/cq-provider-sdk/provider/diag"
	"github.com/cloudquery/cq-provider-sdk/provider/schema"
	"golang.org/x/sync/errgroup"
)

func Aws_cloudwatch_compositealarm() *schema.Table {
  return &schema.Table{
    Name: "cloudcontrol_aws_cloudwatch_compositealarm",
    Description: "aws_cloudwatch_compositealarm",
    Resolver: fetchaws_cloudwatch_compositealarm,
    Multiplex: client.ServiceAccountRegionMultiplexer(""),
    DeleteFilter: client.DeleteAccountRegionFilter,
    Columns: []schema.Column {
    	{
				Name: "account_id",
				Type: schema.TypeString,
			},
      {
				Name: "region",
				Type: schema.TypeString,
			},
      
      {
        Name: "ActionsEnabled",
        Description: `Indicates whether actions should be executed during any changes to the alarm state. The default is TRUE.`,
        Type: schema.TypeBool,
      },
      {
        Name: "AlarmName",
        Description: `The name of the Composite Alarm`,
        Type: schema.TypeString,
      },
      {
        Name: "AlarmDescription",
        Description: `The description of the alarm`,
        Type: schema.TypeString,
      },
      {
        Name: "AlarmRule",
        Description: `Expression which aggregates the state of other Alarms (Metric or Composite Alarms)`,
        Type: schema.TypeString,
      },
      {
        Name: "InsufficientDataActions",
        Description: `The actions to execute when this alarm transitions to the INSUFFICIENT_DATA state from any other state. Each action is specified as an Amazon Resource Name (ARN).`,
        Type: schema.TypeJSON,
      },
      {
        Name: "Arn",
        Description: `Amazon Resource Name (ARN) of the alarm`,
        Type: schema.TypeString,
      },
      {
        Name: "OKActions",
        Description: `The actions to execute when this alarm transitions to the OK state from any other state. Each action is specified as an Amazon Resource Name (ARN).`,
        Type: schema.TypeJSON,
      },
      {
        Name: "AlarmActions",
        Description: `The list of actions to execute when this alarm transitions into an ALARM state from any other state. Specify each action as an Amazon Resource Name (ARN).`,
        Type: schema.TypeJSON,
      },
    },
  }
}


func fetchaws_cloudwatch_compositealarm(ctx context.Context, meta schema.ClientMeta, parent *schema.Resource, res chan<- interface{}) error {
  config := cloudcontrol.ListResourcesInput{
		TypeName:   aws.String("AWS::CloudWatch::CompositeAlarm"),
		MaxResults: aws.Int32(100),
	}
	c := meta.(*client.Client)
  svc := cloudcontrol.NewFromConfig(c.AWSCfg.Copy(), func(o *cloudcontrol.Options) {
		o.Region = c.Region
	})
	for {
		listResources, err := svc.ListResources(ctx, &config)
		if err != nil {
			return diag.WrapError(err)
		}
		// batchResults := make([]map[string]interface{}, len(listResources.ResourceDescriptions))
		errGroup, ctx := errgroup.WithContext(ctx)
		for _, item := range listResources.ResourceDescriptions {
			// i := i
			it := item
			errGroup.Go(func() error {
				r, err := svc.GetResource(ctx, &cloudcontrol.GetResourceInput{
					Identifier: it.Identifier,
					TypeName:   aws.String("AWS::CloudWatch::CompositeAlarm"),
				})
				if err != nil {
					return diag.WrapError(err)
				}
				var resourceJson map[string]interface{}
				if err := json.Unmarshal([]byte(*r.ResourceDescription.Properties), &resourceJson); err != nil {
					return diag.WrapError(err)
				}
				resourceJson["Arn"] = *it.Identifier
				resourceJson["account_id"] = c.AccountID
        resourceJson["region"] = c.Region
				res <- resourceJson
				return nil
			})
		}
		if err := errGroup.Wait(); err != nil {
			return diag.WrapError(err)
		}
		// res <- batchResults
		if aws.ToString(listResources.NextToken) == "" {
			break
		}
		config.NextToken = listResources.NextToken
	}

	return nil
}
