\set framework 'foundational_security'
\set execution_time ''''`date '+%Y-%m-%d %H:%M:%S'`''''::timestamp
\i create_aws_policy_results.sql
\i sql/foundational_security/acm.sql
\i sql/foundational_security/apigateway.sql
\i sql/foundational_security/autoscaling.sql
\i sql/foundational_security/awsconfig.sql
\i sql/foundational_security/cloudfront.sql
\i sql/foundational_security/cloudtrail.sql
\i sql/foundational_security/codebuild.sql
\i sql/foundational_security/dms.sql
\i sql/foundational_security/dynamodb.sql
\i sql/foundational_security/ec2.sql
\i sql/foundational_security/ecs.sql
\i sql/foundational_security/efs.sql
\i sql/foundational_security/elastic_beanstalk.sql
\i sql/foundational_security/elasticsearch.sql
\i sql/foundational_security/elb.sql
\i sql/foundational_security/elbv2.sql
\i sql/foundational_security/emr.sql
\i sql/foundational_security/guardduty.sql
\i sql/foundational_security/iam.sql
\i sql/foundational_security/kms.sql
\i sql/foundational_security/lambda.sql
\i sql/foundational_security/rds.sql
\i sql/foundational_security/redshift.sql
\i sql/foundational_security/s3.sql
\i sql/foundational_security/sagemaker.sql
\i sql/foundational_security/secretmanager.sql
\i sql/foundational_security/sns.sql
\i sql/foundational_security/sqs.sql
\i sql/foundational_security/ssm.sql
\i sql/foundational_security/waf.sql
