// Code generated by internal/generators/main.go; DO NOT EDIT.

package ec2

import (
	"context"
	"encoding/json"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/cloudcontrol"
	"github.com/cloudquery/cq-provider-aws/client"
	"github.com/cloudquery/cq-provider-sdk/provider/diag"
	"github.com/cloudquery/cq-provider-sdk/provider/schema"
	"golang.org/x/sync/errgroup"
)

func Aws_ec2_vpc() *schema.Table {
  return &schema.Table{
    Name: "cloudcontrol_aws_ec2_vpc",
    Description: "aws_ec2_vpc",
    Resolver: fetchaws_ec2_vpc,
    Multiplex: client.ServiceAccountRegionMultiplexer(""),
    DeleteFilter: client.DeleteAccountRegionFilter,
    Columns: []schema.Column {
    	{
				Name: "account_id",
				Type: schema.TypeString,
			},
      {
				Name: "region",
				Type: schema.TypeString,
			},
      
      {
        Name: "DefaultNetworkAcl",
        Description: `The default network ACL ID that is associated with the VPC.`,
        Type: schema.TypeString,
      },
      {
        Name: "DefaultSecurityGroup",
        Description: `The default security group ID that is associated with the VPC.`,
        Type: schema.TypeString,
      },
      {
        Name: "EnableDnsSupport",
        Description: `Indicates whether the DNS resolution is supported for the VPC. If enabled, queries to the Amazon provided DNS server at the 169.254.169.253 IP address, or the reserved IP address at the base of the VPC network range "plus two" succeed. If disabled, the Amazon provided DNS service in the VPC that resolves public DNS hostnames to IP addresses is not enabled. Enabled by default.`,
        Type: schema.TypeBool,
      },
      {
        Name: "VpcId",
        Description: `The Id for the model.`,
        Type: schema.TypeString,
      },
      {
        Name: "CidrBlock",
        Description: `The primary IPv4 CIDR block for the VPC.`,
        Type: schema.TypeString,
      },
      {
        Name: "EnableDnsHostnames",
        Description: `Indicates whether the instances launched in the VPC get DNS hostnames. If enabled, instances in the VPC get DNS hostnames; otherwise, they do not. Disabled by default for nondefault VPCs.`,
        Type: schema.TypeBool,
      },
      {
        Name: "InstanceTenancy",
        Description: `The allowed tenancy of instances launched into the VPC.

"default": An instance launched into the VPC runs on shared hardware by default, unless you explicitly specify a different tenancy during instance launch.

"dedicated": An instance launched into the VPC is a Dedicated Instance by default, unless you explicitly specify a tenancy of host during instance launch. You cannot specify a tenancy of default during instance launch.

Updating InstanceTenancy requires no replacement only if you are updating its value from "dedicated" to "default". Updating InstanceTenancy from "default" to "dedicated" requires replacement.`,
        Type: schema.TypeString,
      },
      {
        Name: "Ipv4IpamPoolId",
        Description: `The ID of an IPv4 IPAM pool you want to use for allocating this VPC's CIDR`,
        Type: schema.TypeString,
      },
      {
        Name: "Ipv4NetmaskLength",
        Description: `The netmask length of the IPv4 CIDR you want to allocate to this VPC from an Amazon VPC IP Address Manager (IPAM) pool`,
        Type: schema.TypeFloat,
      },
      {
        Name: "Tags",
        Description: `The tags for the VPC.`,
        Type: schema.TypeJSON,
      },
      {
        Name: "CidrBlockAssociations",
        Description: `A list of IPv4 CIDR block association IDs for the VPC.`,
        Type: schema.TypeJSON,
      },
      {
        Name: "Ipv6CidrBlocks",
        Description: `A list of IPv6 CIDR blocks that are associated with the VPC.`,
        Type: schema.TypeJSON,
      },
    },
  }
}


func fetchaws_ec2_vpc(ctx context.Context, meta schema.ClientMeta, parent *schema.Resource, res chan<- interface{}) error {
  config := cloudcontrol.ListResourcesInput{
		TypeName:   aws.String("AWS::EC2::VPC"),
		MaxResults: aws.Int32(100),
	}
	c := meta.(*client.Client)
  svc := cloudcontrol.NewFromConfig(c.AWSCfg.Copy(), func(o *cloudcontrol.Options) {
		o.Region = c.Region
	})
	for {
		listResources, err := svc.ListResources(ctx, &config)
		if err != nil {
			return diag.WrapError(err)
		}
		// batchResults := make([]map[string]interface{}, len(listResources.ResourceDescriptions))
		errGroup, ctx := errgroup.WithContext(ctx)
		for _, item := range listResources.ResourceDescriptions {
			// i := i
			it := item
			errGroup.Go(func() error {
				r, err := svc.GetResource(ctx, &cloudcontrol.GetResourceInput{
					Identifier: it.Identifier,
					TypeName:   aws.String("AWS::EC2::VPC"),
				})
				if err != nil {
					return diag.WrapError(err)
				}
				var resourceJson map[string]interface{}
				if err := json.Unmarshal([]byte(*r.ResourceDescription.Properties), &resourceJson); err != nil {
					return diag.WrapError(err)
				}
				resourceJson["Arn"] = *it.Identifier
				resourceJson["account_id"] = c.AccountID
        resourceJson["region"] = c.Region
				res <- resourceJson
				return nil
			})
		}
		if err := errGroup.Wait(); err != nil {
			return diag.WrapError(err)
		}
		// res <- batchResults
		if aws.ToString(listResources.NextToken) == "" {
			break
		}
		config.NextToken = listResources.NextToken
	}

	return nil
}
