-- Autogenerated by migration tool on 2022-04-04 17:12:37
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: codepipeline.pipelines
CREATE TABLE IF NOT EXISTS "aws_codepipeline_pipelines" (
                                                            "cq_id" uuid NOT NULL,
                                                            "cq_meta" jsonb,
                                                            "account_id" text,
                                                            "region" text,
                                                            "tags" jsonb,
                                                            "created" timestamp without time zone,
                                                            "arn" text,
                                                            "updated" timestamp without time zone,
                                                            "name" text,
                                                            "role_arn" text,
                                                            "artifact_store_location" text,
                                                            "artifact_store_type" text,
                                                            "artifact_store_encryption_key_id" text,
                                                            "artifact_store_encryption_key_type" text,
                                                            "artifact_stores" jsonb,
                                                            "version" integer,
                                                            CONSTRAINT aws_codepipeline_pipelines_pk PRIMARY KEY(arn),
                                                            UNIQUE(cq_id)
);
CREATE TABLE IF NOT EXISTS "aws_codepipeline_pipeline_stages" (
                                                                  "cq_id" uuid NOT NULL,
                                                                  "cq_meta" jsonb,
                                                                  "pipeline_cq_id" uuid,
                                                                  "name" text,
                                                                  "blockers" jsonb,
                                                                  CONSTRAINT aws_codepipeline_pipeline_stages_pk PRIMARY KEY(cq_id),
                                                                  UNIQUE(cq_id),
                                                                  FOREIGN KEY (pipeline_cq_id) REFERENCES aws_codepipeline_pipelines(cq_id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aws_codepipeline_pipeline_stage_actions" (
                                                                         "cq_id" uuid NOT NULL,
                                                                         "cq_meta" jsonb,
                                                                         "pipeline_stage_cq_id" uuid,
                                                                         "category" text,
                                                                         "owner" text,
                                                                         "provider" text,
                                                                         "version" text,
                                                                         "name" text,
                                                                         "configuration" jsonb,
                                                                         "input_artifacts" text[],
                                                                         "namespace" text,
                                                                         "output_artifacts" text[],
                                                                         "region" text,
                                                                         "role_arn" text,
                                                                         "run_order" integer,
                                                                         CONSTRAINT aws_codepipeline_pipeline_stage_actions_pk PRIMARY KEY(cq_id),
                                                                         UNIQUE(cq_id),
                                                                         FOREIGN KEY (pipeline_stage_cq_id) REFERENCES aws_codepipeline_pipeline_stages(cq_id) ON DELETE CASCADE
);

-- Resource: sns.subscriptions
ALTER TABLE IF EXISTS aws_sns_subscriptions DROP CONSTRAINT aws_sns_subscriptions_pk;
ALTER TABLE IF EXISTS aws_sns_subscriptions ADD CONSTRAINT aws_sns_subscriptions_pk PRIMARY KEY (endpoint,owner,protocol,arn,topic_arn);
