-- Autogenerated by migration tool on 2022-04-12 11:25:59
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: ec2.egress_only_internet_gateways
DROP TABLE IF EXISTS aws_ec2_egress_only_internet_gateways;
