-- Autogenerated by migration tool on 2022-04-19 08:12:12
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: backup.global_settings
DROP TABLE IF EXISTS aws_backup_global_settings;

-- Resource: backup.region_settings
DROP TABLE IF EXISTS aws_backup_region_settings;
