-- Autogenerated by migration tool on 2022-04-21 12:09:24
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: elasticbeanstalk.application
DROP TABLE IF EXISTS aws_elasticbeanstalk_application_versions;
