-- Autogenerated by migration tool on 2022-05-09 08:55:35
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: xray.groups
DROP TABLE IF EXISTS aws_xray_groups;

-- Resource: xray.sampling_rules
DROP TABLE IF EXISTS aws_xray_sampling_rules;
