-- Autogenerated by migration tool on 2022-05-16 12:13:23
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: iam.groups
ALTER TABLE IF EXISTS "aws_iam_group_policies" DROP COLUMN IF EXISTS "group_id";

CREATE TABLE IF NOT EXISTS "aws_iam_group_accessed_details" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"group_cq_id" uuid,
	"service_name" text,
	"service_namespace" text,
	"last_authenticated" timestamp without time zone,
	"last_authenticated_entity" text,
	"last_authenticated_region" text,
	"total_authenticated_entities" integer,
	CONSTRAINT aws_iam_group_accessed_details_pk PRIMARY KEY(cq_id),
	UNIQUE(cq_id),
	FOREIGN KEY (group_cq_id) REFERENCES aws_iam_groups(cq_id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aws_iam_group_accessed_detail_tracked_actions_last_accessed" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"group_accessed_detail_cq_id" uuid,
	"action_name" text,
	"last_accessed_entity" text,
	"last_accessed_region" text,
	"last_accessed_time" timestamp without time zone,
	CONSTRAINT aws_iam_group_accessed_detail_tracked_actions_last_accessed_pk PRIMARY KEY(cq_id),
	UNIQUE(cq_id),
	FOREIGN KEY (group_accessed_detail_cq_id) REFERENCES aws_iam_group_accessed_details(cq_id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aws_iam_group_accessed_detail_entities" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"group_accessed_detail_cq_id" uuid,
	"arn" text,
	"id" text,
	"name" text,
	"type" text,
	"path" text,
	"last_authenticated" timestamp without time zone,
	CONSTRAINT aws_iam_group_accessed_detail_entities_pk PRIMARY KEY(cq_id),
	UNIQUE(cq_id),
	FOREIGN KEY (group_accessed_detail_cq_id) REFERENCES aws_iam_group_accessed_details(cq_id) ON DELETE CASCADE
);
