-- Autogenerated by migration tool on 2022-05-19 06:55:01
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: iam.access_advisor_details
DROP TABLE IF EXISTS aws_iam_access_advisor_tracked_actions_last_accessed;
DROP TABLE IF EXISTS aws_iam_access_advisor_entities;
DROP TABLE IF EXISTS aws_iam_access_advisor;
