-- Autogenerated by migration tool on 2022-04-20 09:40:27
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: shield.protections
CREATE TABLE IF NOT EXISTS "aws_shield_protections" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"account_id" text,
	"region" text,
	"tags" jsonb,
	"application_layer_automatic_response_configuration_status" text,
	"health_check_ids" text[],
	"id" text,
	"name" text,
	"arn" text,
	"resource_arn" text,
	CONSTRAINT aws_shield_protections_pk PRIMARY KEY(arn),
	UNIQUE(cq_id)
);
