// Code generated by internal/generators/main.go; DO NOT EDIT.

package redshift

import (
	"context"
	"encoding/json"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/cloudcontrol"
	"github.com/cloudquery/cq-provider-aws/client"
	"github.com/cloudquery/cq-provider-sdk/provider/diag"
	"github.com/cloudquery/cq-provider-sdk/provider/schema"
	"golang.org/x/sync/errgroup"
)

func Aws_redshift_cluster() *schema.Table {
  return &schema.Table{
    Name: "cloudcontrol_aws_redshift_cluster",
    Description: "aws_redshift_cluster",
    Resolver: fetchaws_redshift_cluster,
    Multiplex: client.ServiceAccountRegionMultiplexer(""),
    DeleteFilter: client.DeleteAccountRegionFilter,
    Columns: []schema.Column {
    	{
				Name: "account_id",
				Type: schema.TypeString,
			},
      {
				Name: "region",
				Type: schema.TypeString,
			},
      
      {
        Name: "ClusterParameterGroupName",
        Description: `The name of the parameter group to be associated with this cluster.`,
        Type: schema.TypeString,
      },
      {
        Name: "HsmClientCertificateIdentifier",
        Description: `Specifies the name of the HSM client certificate the Amazon Redshift cluster uses to retrieve the data encryption keys stored in an HSM`,
        Type: schema.TypeString,
      },
      {
        Name: "KmsKeyId",
        Description: `The AWS Key Management Service (KMS) key ID of the encryption key that you want to use to encrypt data in the cluster.`,
        Type: schema.TypeString,
      },
      {
        Name: "DestinationRegion",
        Description: `The destination AWS Region that you want to copy snapshots to. Constraints: Must be the name of a valid AWS Region. For more information, see Regions and Endpoints in the Amazon Web Services [https://docs.aws.amazon.com/general/latest/gr/rande.html#redshift_region] General Reference`,
        Type: schema.TypeString,
      },
      {
        Name: "MasterUserPassword",
        Description: `The password associated with the master user account for the cluster that is being created. Password must be between 8 and 64 characters in length, should have at least one uppercase letter.Must contain at least one lowercase letter.Must contain one number.Can be any printable ASCII character.`,
        Type: schema.TypeString,
      },
      {
        Name: "ClusterType",
        Description: `The type of the cluster. When cluster type is specified as single-node, the NumberOfNodes parameter is not required and if multi-node, the NumberOfNodes parameter is required`,
        Type: schema.TypeString,
      },
      {
        Name: "PreferredMaintenanceWindow",
        Description: `The weekly time range (in UTC) during which automated cluster maintenance can occur.`,
        Type: schema.TypeString,
      },
      {
        Name: "PubliclyAccessible",
        Description: `If true, the cluster can be accessed from a public network.`,
        Type: schema.TypeBool,
      },
      {
        Name: "SnapshotCopyGrantName",
        Description: `The name of the snapshot copy grant to use when snapshots of an AWS KMS-encrypted cluster are copied to the destination region.`,
        Type: schema.TypeString,
      },
      {
        Name: "DeferMaintenanceDuration",
        Description: `An integer indicating the duration of the maintenance window in days. If you specify a duration, you can't specify an end time. The duration must be 45 days or less.`,
        Type: schema.TypeFloat,
      },
      {
        Name: "ClusterSubnetGroupName",
        Description: `The name of a cluster subnet group to be associated with this cluster.`,
        Type: schema.TypeString,
      },
      {
        Name: "DBName",
        Description: `The name of the first database to be created when the cluster is created. To create additional databases after the cluster is created, connect to the cluster with a SQL client and use SQL commands to create a database.`,
        Type: schema.TypeString,
      },
      {
        Name: "Encrypted",
        Description: `If true, the data in the cluster is encrypted at rest.`,
        Type: schema.TypeBool,
      },
      {
        Name: "ManualSnapshotRetentionPeriod",
        Description: `The number of days to retain newly copied snapshots in the destination AWS Region after they are copied from the source AWS Region. If the value is -1, the manual snapshot is retained indefinitely.

The value must be either -1 or an integer between 1 and 3,653.`,
        Type: schema.TypeFloat,
      },
      {
        Name: "RevisionTarget",
        Description: `The identifier of the database revision. You can retrieve this value from the response to the DescribeClusterDbRevisions request.`,
        Type: schema.TypeString,
      },
      {
        Name: "RotateEncryptionKey",
        Description: `A boolean indicating if we want to rotate Encryption Keys.`,
        Type: schema.TypeBool,
      },
      {
        Name: "MasterUsername",
        Description: `The user name associated with the master user account for the cluster that is being created. The user name can't be PUBLIC and first character must be a letter.`,
        Type: schema.TypeString,
      },
      {
        Name: "AutomatedSnapshotRetentionPeriod",
        Description: `The number of days that automated snapshots are retained. If the value is 0, automated snapshots are disabled. Default value is 1`,
        Type: schema.TypeFloat,
      },
      {
        Name: "AquaConfigurationStatus",
        Description: `The value represents how the cluster is configured to use AQUA (Advanced Query Accelerator) after the cluster is restored. Possible values include the following.

enabled - Use AQUA if it is available for the current Region and Amazon Redshift node type.
disabled - Don't use AQUA.
auto - Amazon Redshift determines whether to use AQUA.
`,
        Type: schema.TypeString,
      },
      {
        Name: "MaintenanceTrackName",
        Description: `The name for the maintenance track that you want to assign for the cluster. This name change is asynchronous. The new track name stays in the PendingModifiedValues for the cluster until the next maintenance window. When the maintenance track changes, the cluster is switched to the latest cluster release available for the maintenance track. At this point, the maintenance track name is applied.`,
        Type: schema.TypeString,
      },
      {
        Name: "DeferMaintenanceEndTime",
        Description: `A timestamp indicating end time for the deferred maintenance window. If you specify an end time, you can't specify a duration.`,
        Type: schema.TypeString,
      },
      {
        Name: "ClusterIdentifier",
        Description: `A unique identifier for the cluster. You use this identifier to refer to the cluster for any subsequent cluster operations such as deleting or modifying. All alphabetical characters must be lower case, no hypens at the end, no two consecutive hyphens. Cluster name should be unique for all clusters within an AWS account`,
        Type: schema.TypeString,
      },
      {
        Name: "Port",
        Description: `The port number on which the cluster accepts incoming connections. The cluster is accessible only via the JDBC and ODBC connection strings`,
        Type: schema.TypeFloat,
      },
      {
        Name: "OwnerAccount",
        Description: ``,
        Type: schema.TypeString,
      },
      {
        Name: "AvailabilityZoneRelocationStatus",
        Description: `The availability zone relocation status of the cluster`,
        Type: schema.TypeString,
      },
      {
        Name: "EnhancedVpcRouting",
        Description: `An option that specifies whether to create the cluster with enhanced VPC routing enabled. To create a cluster that uses enhanced VPC routing, the cluster must be in a VPC. For more information, see Enhanced VPC Routing in the Amazon Redshift Cluster Management Guide.

If this option is true , enhanced VPC routing is enabled.

Default: false`,
        Type: schema.TypeBool,
      },
      {
        Name: "DeferMaintenance",
        Description: `A boolean indicating whether to enable the deferred maintenance window.`,
        Type: schema.TypeBool,
      },
      {
        Name: "DeferMaintenanceIdentifier",
        Description: `A unique identifier for the deferred maintenance window.`,
        Type: schema.TypeString,
      },
      {
        Name: "AvailabilityZone",
        Description: `The EC2 Availability Zone (AZ) in which you want Amazon Redshift to provision the cluster. Default: A random, system-chosen Availability Zone in the region that is specified by the endpoint`,
        Type: schema.TypeString,
      },
      {
        Name: "HsmConfigurationIdentifier",
        Description: `Specifies the name of the HSM configuration that contains the information the Amazon Redshift cluster can use to retrieve and store keys in an HSM.`,
        Type: schema.TypeString,
      },
      {
        Name: "IamRoles",
        Description: `A list of AWS Identity and Access Management (IAM) roles that can be used by the cluster to access other AWS services. You must supply the IAM roles in their Amazon Resource Name (ARN) format. You can supply up to 10 IAM roles in a single request`,
        Type: schema.TypeJSON,
      },
      {
        Name: "LoggingProperties",
        Description: ``,
        Type: schema.TypeJSON,
      },
      {
        Name: "NodeType",
        Description: `The node type to be provisioned for the cluster.Valid Values: ds2.xlarge | ds2.8xlarge | dc1.large | dc1.8xlarge | dc2.large | dc2.8xlarge | ra3.4xlarge | ra3.16xlarge`,
        Type: schema.TypeString,
      },
      {
        Name: "AllowVersionUpgrade",
        Description: `Major version upgrades can be applied during the maintenance window to the Amazon Redshift engine that is running on the cluster. Default value is True`,
        Type: schema.TypeBool,
      },
      {
        Name: "ClusterSecurityGroups",
        Description: `A list of security groups to be associated with this cluster.`,
        Type: schema.TypeJSON,
      },
      {
        Name: "Tags",
        Description: `The list of tags for the cluster parameter group.`,
        Type: schema.TypeJSON,
      },
      {
        Name: "VpcSecurityGroupIds",
        Description: `A list of Virtual Private Cloud (VPC) security groups to be associated with the cluster.`,
        Type: schema.TypeJSON,
      },
      {
        Name: "SnapshotCopyRetentionPeriod",
        Description: `The number of days to retain automated snapshots in the destination region after they are copied from the source region. 

 Default is 7. 

 Constraints: Must be at least 1 and no more than 35.`,
        Type: schema.TypeFloat,
      },
      {
        Name: "ResourceAction",
        Description: `The Redshift operation to be performed. Resource Action supports pause-cluster, resume-cluster APIs`,
        Type: schema.TypeString,
      },
      {
        Name: "ClusterVersion",
        Description: `The version of the Amazon Redshift engine software that you want to deploy on the cluster.The version selected runs on all the nodes in the cluster.`,
        Type: schema.TypeString,
      },
      {
        Name: "ElasticIp",
        Description: `The Elastic IP (EIP) address for the cluster.`,
        Type: schema.TypeString,
      },
      {
        Name: "NumberOfNodes",
        Description: `The number of compute nodes in the cluster. This parameter is required when the ClusterType parameter is specified as multi-node.`,
        Type: schema.TypeFloat,
      },
      {
        Name: "SnapshotClusterIdentifier",
        Description: `The name of the cluster the source snapshot was created from. This parameter is required if your IAM user has a policy containing a snapshot resource element that specifies anything other than * for the cluster name.`,
        Type: schema.TypeString,
      },
      {
        Name: "SnapshotIdentifier",
        Description: `The name of the snapshot from which to create the new cluster. This parameter isn't case sensitive.`,
        Type: schema.TypeString,
      },
      {
        Name: "Id",
        Description: ``,
        Type: schema.TypeString,
      },
      {
        Name: "Endpoint",
        Description: ``,
        Type: schema.TypeJSON,
      },
      {
        Name: "SnapshotCopyManual",
        Description: `Indicates whether to apply the snapshot retention period to newly copied manual snapshots instead of automated snapshots.`,
        Type: schema.TypeBool,
      },
      {
        Name: "AvailabilityZoneRelocation",
        Description: `The option to enable relocation for an Amazon Redshift cluster between Availability Zones after the cluster modification is complete.`,
        Type: schema.TypeBool,
      },
      {
        Name: "Classic",
        Description: `A boolean value indicating whether the resize operation is using the classic resize process. If you don't provide this parameter or set the value to false , the resize type is elastic.`,
        Type: schema.TypeBool,
      },
      {
        Name: "DeferMaintenanceStartTime",
        Description: `A timestamp indicating the start time for the deferred maintenance window.`,
        Type: schema.TypeString,
      },
    },
  }
}


func fetchaws_redshift_cluster(ctx context.Context, meta schema.ClientMeta, parent *schema.Resource, res chan<- interface{}) error {
  config := cloudcontrol.ListResourcesInput{
		TypeName:   aws.String("AWS::Redshift::Cluster"),
		MaxResults: aws.Int32(100),
	}
	c := meta.(*client.Client)
  svc := cloudcontrol.NewFromConfig(c.AWSCfg.Copy(), func(o *cloudcontrol.Options) {
		o.Region = c.Region
	})
	for {
		listResources, err := svc.ListResources(ctx, &config)
		if err != nil {
			return diag.WrapError(err)
		}
		// batchResults := make([]map[string]interface{}, len(listResources.ResourceDescriptions))
		errGroup, ctx := errgroup.WithContext(ctx)
		for _, item := range listResources.ResourceDescriptions {
			// i := i
			it := item
			errGroup.Go(func() error {
				r, err := svc.GetResource(ctx, &cloudcontrol.GetResourceInput{
					Identifier: it.Identifier,
					TypeName:   aws.String("AWS::Redshift::Cluster"),
				})
				if err != nil {
					return diag.WrapError(err)
				}
				var resourceJson map[string]interface{}
				if err := json.Unmarshal([]byte(*r.ResourceDescription.Properties), &resourceJson); err != nil {
					return diag.WrapError(err)
				}
				resourceJson["Arn"] = *it.Identifier
				resourceJson["account_id"] = c.AccountID
        resourceJson["region"] = c.Region
				res <- resourceJson
				return nil
			})
		}
		if err := errGroup.Wait(); err != nil {
			return diag.WrapError(err)
		}
		// res <- batchResults
		if aws.ToString(listResources.NextToken) == "" {
			break
		}
		config.NextToken = listResources.NextToken
	}

	return nil
}
