# DONT EDIT. This file is synced from https://github.com/cloudquery/.github/.github
name: check_generated_code
on:
  push:
    branches:
      - main
      - check-cq-gen
  pull_request:
    branches:
      - main

jobs:
  lint_doc:
    name: Check Generated Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '!(terraform/**/*|scripts/**/*)'
      - name: Set up Go 1.x
        if: steps.changes.outputs.src == 'true' || github.event_name != 'pull_request'
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
      - uses: actions/cache@v3
        if: steps.changes.outputs.src == 'true' || github.event_name != 'pull_request'
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}-
      - name: go-generate
        if: steps.changes.outputs.src == 'true' || github.event_name != 'pull_request'
        run: |
          | for d in ./resources/services/*/ ; do
          |   if grep -s -q '//check-for-changes' "$d"*.hcl; then
          |    (cd $d && go generate);
          |    fi
          | done
      - name: Fail if any files are changed
        if: steps.changes.outputs.src == 'true' || github.event_name != 'pull_request'
        run: |
          test "$(git status -s ./resources/services | wc -l)" -eq 0