name: golangci-lint
on:
  push:
    branches:
      - main

jobs:
  endpoints:
    name: aws endpoints verification
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: regenerate partition_service_region file
        run: |
          go run ./tools/endpoints/main.go
      - name: Fail if file is changed
        run: |
          test "$(git status -s ./client/data/partition_service_region.json | wc -l)" -eq 0
