# DONT EDIT. This file is synced from https://github.com/cloudquery/.github/.github
name: lint_doc
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_doc:
    name: Lint Provider Doc
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: remove all docs
        run: |
          rm -f ./docs/tables/*.md
      - name: build-docs
        run: |
          go run ./docs/docs.go
      - name: Fail if docs are changed
        run: |
          test "$(git status -s ./docs/tables | wc -l)" -eq 0