# DONT EDIT. This file is synced from https://github.com/cloudquery/.github/.github
name: lint_doc
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_doc:
    name: Lint Provider Doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '!(terraform/**/*|scripts/**/*)'
      - name: Set up Go 1.x
        if: steps.changes.outputs.src == 'true' || github.event_name != 'pull_request'
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
      - uses: actions/cache@v3
        if: steps.changes.outputs.src == 'true' || github.event_name != 'pull_request'
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}-
      - name: remove all docs
        if: steps.changes.outputs.src == 'true' || github.event_name != 'pull_request'
        run: |
          rm -f ./docs/tables/*.md
      - name: build-docs
        if: steps.changes.outputs.src == 'true' || github.event_name != 'pull_request'
        run: |
          go run ./docs/docs.go
      - name: Fail if docs are changed
        if: steps.changes.outputs.src == 'true' || github.event_name != 'pull_request'
        run: |
          test "$(git status -s ./docs/tables | wc -l)" -eq 0