name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1

  docs:
    name: docs verification
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: remove all docs
        run: |
          rm -f ./docs/tables/*.md
      - name: build-docs
        run: |
          go run ./docs/docs.go
      - name: Fail if docs are changed
        run: |
          test "$(git status -s ./docs/tables | wc -l)" -eq 0
