name: Dispatch Test Command

on:
  issue_comment:
    types: [created]

jobs:
  manual-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AWS provider integration tests 
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GH_CQ_BOT }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: pull-request
          commands: test
          permission: write