name: terraform_plan
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  terrafrom_plan:
    name: Terrafrom plan
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Check for terrafrom files changes
        run: |
          test "$(git diff --name-only $(git merge-base main HEAD) | grep "terrafrom/*" | wc -l)" -eq 0
        continue-on-error: true

      - name: Terraform plan for changes
        if: failure()
        run: |
          cd terrafrom
          terraform apply