# DONT EDIT. This file is synced from https://github.com/cloudquery/.github/.github
name: terraform_apply
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terrafrom_apply:
    permissions:
        id-token: write
        contents: read    # This is required for actions/checkout@v2
    name: Terrafrom Apply
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.17

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::707066037989:role/cq-provider-aws-github-action
          aws-region: us-east-1
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Apply
        id: apply
        run: ./scripts/terraform-apply-changes-only.sh
