auth_step: |
    {{=<% %>=}}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::707066037989:role/cq-provider-aws-github-action
        aws-region: us-east-1

name: "aws"