{{! the empty template/value use below tells github to use this file only if we have a .values.yml file for the provider }}
{{=<% %>=}}

# DONT EDIT. This file is synced from https://github.com/cloudquery/.github/.github
name: SQL Policy Validation Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CGO_ENABLED: 0
  CQ_NO_TELEMETRY: 1
  PGPASSWORD: pass

jobs:
  SQLPolicyTest:
    strategy:
      matrix:
        dbversion: [ "postgres:10" ]
        go: [ "1.18" ]
        platform: [ ubuntu-latest ] # can not run in macOS and widnowsOS
    runs-on: ${{ matrix.platform }}
    services:
      postgres:
        image: ${{ matrix.dbversion }}
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code into the policy directory
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}-

      - name: Prepare for test - Create tables
        run: |
          go run ./test/gen-tables.go | psql -h localhost -p 5432 -U postgres -d postgres -w

      - name: Run all policies
        run: |
          cd policies && psql -h localhost -p 5432 -U postgres -d postgres -w -f ./policy.sql
