# DONT EDIT. This file is synced from https://github.com/cloudquery/.github/.github
name: test_integration

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'

jobs:
  is_organization_member:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.is_organization_member.outputs.result }}
    steps:
      - uses: yevgenypats/is-organization-member@646ee210c04d55d8b7f3a591722d06eb16310236
        if: github.event_name == 'pull_request_target'
        id: is_organization_member
        with:
          organization: cloudquery
          username: ${{ github.event.pull_request.user.login }}
          token: ${{ secrets.GH_PAT }}  
      - name: Skip if not member and event is pull_request_target
        if: github.event_name != 'pull_request_target' || steps.is_organization_member.outputs.result == 'false'
        run: |
            echo ${{ steps.is_organization_member.outputs }}
            echo "user ${{ github.event.pull_request.user.login }} is not part of org. Please run 'go test -run=TestIntegration -tags=integration ./..'"
            echo "and paste the output in the PR"

  test_integration:
    permissions:
        id-token: write
        contents: read    # This is required for actions/checkout@v2
    needs: is_organization_member
    if: github.event_name != 'pull_request_target' || needs.is_organization_member.outputs.status == 'true'
    strategy:
      matrix:
        dbversion: [ "postgres:latest" ]
        go: [ "1.17" ]
        platform: [ ubuntu-latest ] # can not run in macOS and windowsOS
    runs-on: ${{ matrix.platform }}
    services:
      postgres:
        image: ${{ matrix.dbversion }}
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16


      - name: Check out code into the Go module directory
        if: github.event_name != 'pull_request_target'
        uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::707066037989:role/cq-provider-aws-github-action
          aws-region: us-east-1

      - name: Integration Test
        run: |
          go test -run=TestIntegration -tags=integration ./...

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{  github.event_name != 'pull_request_target' && failure() }}
        env:
          SLACK_CHANNEL: oss-tests
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'aws - E2E tests failed'
          SLACK_TITLE: aws - E2E tests failed
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
